// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvBDgsacBs6ShYbsDqZEB89rq7BT6jyG4',
    appId: '1:159445462515:web:37e34f0c5f51a9f6933686',
    messagingSenderId: '159445462515',
    projectId: 'aureola-5e3dd',
    authDomain: 'aureola-5e3dd.firebaseapp.com',
    storageBucket: 'aureola-5e3dd.firebasestorage.app',
    measurementId: 'G-39Q2H5367Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdKz-WfiKWjF50BgULosu0Hs6KoIUZHto',
    appId: '1:159445462515:android:d8979af035f89fc8933686',
    messagingSenderId: '159445462515',
    projectId: 'aureola-5e3dd',
    storageBucket: 'aureola-5e3dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdsh_TKHMxxb2Cr_EVXCdlKcT29wIIFS8',
    appId: '1:159445462515:ios:f35e8e815f0dfaef933686',
    messagingSenderId: '159445462515',
    projectId: 'aureola-5e3dd',
    storageBucket: 'aureola-5e3dd.firebasestorage.app',
    iosBundleId: 'com.example.aureolaPlatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdsh_TKHMxxb2Cr_EVXCdlKcT29wIIFS8',
    appId: '1:159445462515:ios:f35e8e815f0dfaef933686',
    messagingSenderId: '159445462515',
    projectId: 'aureola-5e3dd',
    storageBucket: 'aureola-5e3dd.firebasestorage.app',
    iosBundleId: 'com.example.aureolaPlatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvBDgsacBs6ShYbsDqZEB89rq7BT6jyG4',
    appId: '1:159445462515:web:cad9bbf13f56bf1e933686',
    messagingSenderId: '159445462515',
    projectId: 'aureola-5e3dd',
    authDomain: 'aureola-5e3dd.firebaseapp.com',
    storageBucket: 'aureola-5e3dd.firebasestorage.app',
    measurementId: 'G-HBWKLWH2ZE',
  );

}